apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-app2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-app2
  template:
    metadata:
      labels:
        app: hello-app2
    spec:
      containers:
      - name: app2
        image: nginx:alpine
        ports:
        - containerPort: 80